Player movement
stephendawsondev/j-day pull request #35
Opened 2023-08-18 19:49 UTC by Koko-66

Added character sprites, and basic movement for the player

2023-08-18 21:02 UTC, KTC96 requested changes
I am not sure how to resolve these conflicts

2023-08-18 21:14 UTC, Koko-66 commented
There shouldn't be any conflicts, could you let me where they are?

2023-08-19 07:04 UTC, stephendawsondev approved these changes
It looks good. There may be some merge conflicts. I will resolve any that pop up!

2023-08-19 07:57 UTC, KTC96 approved these changes

2023-08-19 09:06 UTC, merged